In [1]:
import torch
import numpy as np

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else 'mps'
    if torch.backends.mps.is_available()
    else 'cpu'
)

print(f"Using {device} device")

Using cuda device


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
type(x_data)

torch.Tensor

In [4]:
# Numpy array to torch tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Rand tensor: \n {x_rand}\n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])

Rand tensor: 
 tensor([[0.3689, 0.1311],
        [0.9459, 0.5399]])



In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor}\n")
print(f"Ones tensor: \n {ones_tensor}\n")
print(f"Zeros tensor: \n {zeros_tensor}\n")

Random tensor: 
 tensor([[0.3279, 0.1569, 0.0803],
        [0.4553, 0.9102, 0.4854]])

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



### Attributes of a tensor

In [7]:
tensor2 = torch.rand(3, 4)

print(f"Shape of tensor: \n {tensor2.shape}\n")
print(f"Data type of tensor: \n {tensor2.dtype}\n")
print(f"Device tensor is stored on: \n {tensor2.device}\n")

Shape of tensor: 
 torch.Size([3, 4])

Data type of tensor: 
 torch.float32

Device tensor is stored on: 
 cpu



In [8]:
tensor = torch.rand(3, 4).to(device)

print(f"Shape of tensor: \n {tensor.shape}\n")
print(f"Data type of tensor: \n {tensor.dtype}\n")
print(f"Device tensor is stored on: \n {tensor.device}\n")


Shape of tensor: 
 torch.Size([3, 4])

Data type of tensor: 
 torch.float32

Device tensor is stored on: 
 cuda:0



In [9]:
tensor = torch.rand((4, 4), dtype=torch.float)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([0.5384, 0.5497, 0.8584, 0.8641])
First column: tensor([0.5384, 0.4931, 0.5936, 0.1509])
Last column: tensor([0.8641, 0.3096, 0.0994, 0.9055])
tensor([[0.5384, 0.0000, 0.8584, 0.8641],
        [0.4931, 0.0000, 0.1458, 0.3096],
        [0.5936, 0.0000, 0.6606, 0.0994],
        [0.1509, 0.0000, 0.2999, 0.9055]])


In [10]:
# Join tensors
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

t2 = torch.cat([tensor, tensor], dim=0)
print(t2)

tensor([[0.5384, 0.0000, 0.8584, 0.8641, 0.5384, 0.0000, 0.8584, 0.8641],
        [0.4931, 0.0000, 0.1458, 0.3096, 0.4931, 0.0000, 0.1458, 0.3096],
        [0.5936, 0.0000, 0.6606, 0.0994, 0.5936, 0.0000, 0.6606, 0.0994],
        [0.1509, 0.0000, 0.2999, 0.9055, 0.1509, 0.0000, 0.2999, 0.9055]])
tensor([[0.5384, 0.0000, 0.8584, 0.8641],
        [0.4931, 0.0000, 0.1458, 0.3096],
        [0.5936, 0.0000, 0.6606, 0.0994],
        [0.1509, 0.0000, 0.2999, 0.9055],
        [0.5384, 0.0000, 0.8584, 0.8641],
        [0.4931, 0.0000, 0.1458, 0.3096],
        [0.5936, 0.0000, 0.6606, 0.0994],
        [0.1509, 0.0000, 0.2999, 0.9055]])


In [11]:
t3 = torch.stack([tensor, tensor], dim=1)
print(t3)

t4 = torch.stack([tensor, tensor], dim=0)
print(t4)

tensor([[[0.5384, 0.0000, 0.8584, 0.8641],
         [0.5384, 0.0000, 0.8584, 0.8641]],

        [[0.4931, 0.0000, 0.1458, 0.3096],
         [0.4931, 0.0000, 0.1458, 0.3096]],

        [[0.5936, 0.0000, 0.6606, 0.0994],
         [0.5936, 0.0000, 0.6606, 0.0994]],

        [[0.1509, 0.0000, 0.2999, 0.9055],
         [0.1509, 0.0000, 0.2999, 0.9055]]])
tensor([[[0.5384, 0.0000, 0.8584, 0.8641],
         [0.4931, 0.0000, 0.1458, 0.3096],
         [0.5936, 0.0000, 0.6606, 0.0994],
         [0.1509, 0.0000, 0.2999, 0.9055]],

        [[0.5384, 0.0000, 0.8584, 0.8641],
         [0.4931, 0.0000, 0.1458, 0.3096],
         [0.5936, 0.0000, 0.6606, 0.0994],
         [0.1509, 0.0000, 0.2999, 0.9055]]])


### Arithmetic operations

In [12]:
# Matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.7734, 0.6582, 0.9726, 1.1211],
        [0.6582, 0.3602, 0.4198, 0.3985],
        [0.9726, 0.4198, 0.7987, 0.3777],
        [1.1211, 0.3985, 0.3777, 0.9326]])

In [14]:
# Element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.2898, 0.0000, 0.7369, 0.7466],
        [0.2431, 0.0000, 0.0213, 0.0959],
        [0.3524, 0.0000, 0.4364, 0.0099],
        [0.0228, 0.0000, 0.0899, 0.8199]])

In [15]:
# Single element tensors
agg = tensor.sum()
print("agg: ", agg, type(agg))

agg_item = agg.item()
print("agg_item: ", agg_item, type(agg_item))

agg:  tensor(5.9193) <class 'torch.Tensor'>
agg_item:  5.919267654418945 <class 'float'>


In [16]:
# In-place operations -- result stored into the operand
print(f"{tensor} \n")
tensor.add_(5)
print(f"{tensor} \n")

tensor([[0.5384, 0.0000, 0.8584, 0.8641],
        [0.4931, 0.0000, 0.1458, 0.3096],
        [0.5936, 0.0000, 0.6606, 0.0994],
        [0.1509, 0.0000, 0.2999, 0.9055]]) 

tensor([[5.5384, 5.0000, 5.8584, 5.8641],
        [5.4931, 5.0000, 5.1458, 5.3096],
        [5.5936, 5.0000, 5.6606, 5.0994],
        [5.1509, 5.0000, 5.2999, 5.9055]]) 



### Bridge with numpy

In [18]:
t = torch.ones(5,)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [19]:
# Both variables point to the same memory location
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [21]:
n = np.ones(4,)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1.]
t: tensor([1., 1., 1., 1.], dtype=torch.float64)


In [22]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2.]
t: tensor([2., 2., 2., 2.], dtype=torch.float64)
